#!/usr/bin/env bash

# Source global definitions
[ -r /etc/bashrc ] && . /etc/bashrc
[ -r /etc/bash.bashrc ] && . /etc/bash.bashrc

# Set the shell prompt.  See the bash man page for a description-
# of special characters.
export PS1='[\[\e[0;36m\]\u\[\e[0;37m\]@\[\e[0;35m\]\h \[\e[0;34m\]\w\[\e[00m\]] '
