#!/bin/sh

# Add a directory for user executables
export PATH=$HOME/bin:$PATH

# Create aliases for commonly used commands.-
alias ls="ls --color=auto -G"
alias la="ls --color=auto -al -G"
alias ll="ls --color=auto -l -G"

# Use virtualenv where possible
if [ -f /usr/bin/virtualenvwrapper.sh ]; then
	export WORKON_HOME=$HOME/.virtualenvs
	source /usr/bin/virtualenvwrapper.sh
fi
if [ -f $HOME/bin/virtualenvwrapper.sh ]; then
	export WORKON_HOME=$HOME/.virtualenvs
	source $HOME/bin/virtualenvwrapper.sh
fi

# Hack to make moving around virtualenvs easier
# On cd, if a .venv file exists, workon the contents
has_virtualenv() {
    if [[ -e .venv && ! -z $WORKON_HOME ]]; then
        CURRENT_VENV=$WORKON_HOME/`cat .venv`
        if [ "$CURRENT_VENV" != "$VIRTUAL_ENV" ]; then
            workon `cat .venv`
        fi
    fi
}
venv_cd () {
    cd "$@" && has_virtualenv
}
alias cd="venv_cd"

# Start rvm when possible
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# Start rbenv
if [ -d "$HOME/.rbenv" ]; then
    export PATH=$HOME/.rbenv/bin:$PATH
    eval "$(rbenv init -)"
fi

# Set up a sane google go environment
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH

# Add readline support to programs
add_readline () {
    socat READLINE EXEC:$1
}
alias rl="add_readline"

# tmux needs special help with coloring
alias tmux="TERM=screen-256color-bce tmux"
