set nocompatible

" Load plugins via Vundle
source ~/.vimrc.plugins

" Security
set modelines=0

" Tabs/spaces
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Basic options
set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
if version >= 703
    set relativenumber
    set colorcolumn=81
    "set undofile
endif

" Backups
set backupdir=~/.vim/tmp/backup// " backups
set directory=~/.vim/tmp/swap//   " swap files
set backup                        " enable backups

" Searching
nnoremap / /\v
vnoremap / /\v
set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch
set gdefault
map <leader><space> :noh<cr>

" Status line
set laststatus=2
set statusline=%-.40f\                  " filename
set statusline+=%y\                     " syntax type
set statusline+=[%{&ff},%{&fenc},       " file settings
set statusline+=%{&et?'spaces':'tabs'}, " expand tabs?
set statusline+=%{&ts}]\                " tabstop width
set statusline+=%h%r%w%m                " flags
set statusline+=%=                      " right align
set statusline+=%{synIDattr(synID(line('.'),col('.'),1),'name')}\  " current syntax element
set statusline+=(%c,%l/%L)\             " cursor position
set statusline+=%P                      " percentage through file

" Color scheme (terminal)
syntax on
set background=dark
set t_Co=256
colorscheme molokai

" NERD Tree
map <F2> :NERDTreeToggle<cr>
let NERDTreeIgnore=['.vim$', '\~$', '.*\.pyc$', 'pip-log\.txt$']

" Nice pasting
set pastetoggle=<leader>p

" Guess the tab format of the current file
function! GuessExpandTab()
    let nspaces = len(filter(getline(0, "$"), 'match(v:val, " ") == 0'))
    let ntabs = len(filter(getline(0, "$"), 'match(v:val, "\t") == 0'))
    if ntabs > nspaces
        set noexpandtab
    endif
endfunction

" Guess tab format here, override after
au BufRead * call GuessExpandTab()

au BufRead,BufNewFile *.less set filetype=css
au BufRead,BufNewFile *.scss set filetype=scss

au BufNewFile,BufRead *.m{ark,}d{own,} set filetype=markdown
au BufNewFile,BufRead *.m{ark,}d{own,} nnoremap <leader>1 yypVr=
au BufNewFile,BufRead *.m{ark,}d{own,} nnoremap <leader>2 yypVr-
au BufNewFile,BufRead *.m{ark,}d{own,} nnoremap <leader>3 I### <ESC>

au BufNewFile,BufRead *.{s,}ml set tabstop=2
au BufNewFile,BufRead *.{s,}ml set shiftwidth=2
au BufNewFile,BufRead *.{s,}ml set softtabstop=2

au BufNewFile,BufRead *.go set noexpandtab

" Highlight trailing whitespace
highlight ExtraWhitespace ctermbg=darkgrey guibg=darkgrey
function! SetExtraWhitespace()
    if &expandtab
        match ExtraWhitespace /^\t+\|\s\+$/
    else
        match ExtraWhitespace /^ +\|\s\+$/
    endif
endfunction
au BufWinEnter * call SetExtraWhitespace()
au BufWinLeave * call clearmatches()
au InsertEnter * call clearmatches()
au InsertLeave * call SetExtraWhitespace()

" TagList
nnoremap <leader>t :TlistToggle<cr>

" LatexSuite
let g:Tex_DefaultTargetFormat='pdf'
let g:Imap_UsePlaceHolders=0

" Gundo
nnoremap <leader>u :GundoToggle<cr>

" Edit .vimrc
nnoremap <leader>ev :e $MYVIMRC<cr>

" Sudo to write
cmap w!! w !sudo tee % >/dev/null

" Shouldn't need shift
nnoremap ; :
nnoremap , ;

" For colemak users
nnoremap <leader>k :set langmap=nj,ek,kn,je<cr>
nnoremap <leader>n :set langmap=<cr>
set langmap=nj,ek,kn,je
